### ISSUE TITLE
NilClass#homepage (ActionView::Template::Error) "Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true"

### ISSUE THREAD

**Issue by stgm** [uva/course-site#304]
<table><tr><th>Exception</th><td>Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true</td></tr><tr><th>Last Occurrence</th><td>June 25, 2015 01:29:25 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/actionpack-4.0.4/lib/action_dispatch/http/url.rb:59:in `build_host_url'
[bundle].../gems/actionpack-4.0.4/lib/action_dispatch/http/url.rb:40:in `url_for'
[bundle].../gems/actionpack-4.0.4/lib/action_dispatch/routing/route_set.rb:177:in `call'
[bundle].../gems/actionpack-4.0.4/lib/action_dispatch/routing/route_set.rb:268:in `block (2 levels) in define_url_helper'
<a href='https://github.com/uva/course-site/blob/7333a9a4b622bdf6003150ab3fa54d22d7b772fc/app/views/page/_content.html.erb#L25'>[app].../app/views/page/_content.html.erb:25:in `_app_views_page__content_html_erb___748339649152531083_70332302544900'</a>
[bundle].../gems/actionpack-4.0.4/lib/action_view/template.rb:143:in `block in render'
[bundle].../gems/activesupport-4.0.4/lib/active_support/notifications.rb:161:in `instrument'
[bundle].../gems/actionpack-4.0.4/lib/action_view/template.rb:141:in `render'
[bundle].../gems/actionpack-4.0.4/lib/action_view/renderer/partial_renderer.rb:306:in `render_partial'
[bundle].../gems/actionpack-4.0.4/lib/action_view/renderer/partial_renderer.rb:279:in `block in render'
[bundle].../gems/actionpack-4.0.4/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
[bundle].../gems/activesupport-4.0.4/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.0.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.0.4/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionpack-4.0.4/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
[bundle].../gems/actionpack-4.0.4/lib/action_view/renderer/partial_renderer.rb:278:in `render'
[bundle].../gems/actionpack-4.0.4/lib/action_view/renderer/renderer.rb:47:in `render_partial'
[bundle].../gems/actionpack-4.0.4/lib/action_view/helpers/rendering_helper.rb:27:in `render'
<a href='https://github.com/uva/course-site/blob/7333a9a4b622bdf6003150ab3fa54d22d7b772fc/app/views/page/index.html.erb#L5'>[app].../app/views/page/index.html.erb:5:in `_app_views_page_index_html_erb___1558329035909251013_70332302448080'</a>
[bundle].../gems/actionpack-4.0.4/lib/action_view/template.rb:143:in `block in render'
[bundle].../gems/activesupport-4.0.4/lib/active_support/notifications.rb:161:in `instrument'
[bundle].../gems/actionpack-4.0.4/lib/action_view/template.rb:141:in `render'
[bundle].../gems/actionpack-4.0.4/lib/action_view/renderer/template_renderer.rb:49:in `block (2 levels) in render_template'
[bundle].../gems/actionpack-4.0.4/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
[bundle].../gems/activesupport-4.0.4/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.0.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.0.4/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionpack-4.0.4/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
[bundle].../gems/actionpack-4.0.4/lib/action_view/renderer/template_renderer.rb:48:in `block in render_template'
[bundle].../gems/actionpack-4.0.4/lib/action_view/renderer/template_renderer.rb:56:in `render_with_layout'
[bundle].../gems/actionpack-4.0.4/lib/action_view/renderer/template_renderer.rb:47:in `render_template'
[bundle].../gems/actionpack-4.0.4/lib/action_view/renderer/template_renderer.rb:17:in `render'
[bundle].../gems/actionpack-4.0.4/lib/action_view/renderer/renderer.rb:42:in `render_template'
[bundle].../gems/actionpack-4.0.4/lib/action_view/renderer/renderer.rb:23:in `render'
[bundle].../gems/actionpack-4.0.4/lib/abstract_controller/rendering.rb:127:in `_render_template'
[bundle].../gems/actionpack-4.0.4/lib/action_controller/metal/streaming.rb:219:in `_render_template'
[bundle].../gems/actionpack-4.0.4/lib/abstract_controller/rendering.rb:120:in `render_to_body'
[bundle].../gems/actionpack-4.0.4/lib/action_controller/metal/rendering.rb:33:in `render_to_body'
[bundle].../gems/actionpack-4.0.4/lib/action_controller/metal/renderers.rb:26:in `render_to_body'
[bundle].../gems/actionpack-4.0.4/lib/abstract_controller/rendering.rb:97:in `render'
[bundle].../gems/actionpack-4.0.4/lib/action_controller/metal/rendering.rb:16:in `render'
[bundle].../gems/actionpack-4.0.4/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
[bundle].../gems/activesupport-4.0.4/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
[bundle].../gems/activesupport-4.0.4/lib/active_support/core_ext/benchmark.rb:12:in `ms'
[bundle].../gems/actionpack-4.0.4/lib/action_controller/metal/instrumentation.rb:41:in `block in render'
[bundle].../gems/actionpack-4.0.4/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
[bundle].../gems/activerecord-4.0.4/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
[bundle].../gems/actionpack-4.0.4/lib/action_controller/metal/instrumentation.rb:40:in `render'
<a href='https://github.com/uva/course-site/blob/7333a9a4b622bdf6003150ab3fa54d22d7b772fc/app/controllers/page_controller.rb#L18'>[app].../app/controllers/page_controller.rb:18:in `homepage'</a>
[bundle].../gems/actionpack-4.0.4/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-4.0.4/lib/abstract_controller/base.rb:189:in `process_action'
[bundle].../gems/actionpack-4.0.4/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.0.4/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
[bundle].../gems/activesupport-4.0.4/lib/active_support/callbacks.rb:423:in `_run__1307508538215579098__process_action__callbacks'
[bundle].../gems/activesupport-4.0.4/lib/active_support/callbacks.rb:80:in `run_callbacks'
[bundle].../gems/actionpack-4.0.4/lib/abstract_controller/callbacks.rb:17:in `process_action'
[bundle].../gems/actionpack-4.0.4/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.0.4/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
[bundle].../gems/activesupport-4.0.4/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.0.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.0.4/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionpack-4.0.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.0.4/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.0.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.0.4/lib/abstract_controller/base.rb:136:in `process'
[bundle].../gems/actionpack-4.0.4/lib/abstract_controller/rendering.rb:44:in `process'
[bundle].../gems/actionpack-4.0.4/lib/action_controller/metal.rb:195:in `dispatch'
[bundle].../gems/actionpack-4.0.4/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.0.4/lib/action_controller/metal.rb:231:in `block in action'
[bundle].../gems/actionpack-4.0.4/lib/action_dispatch/routing/route_set.rb:80:in `call'
[bundle].../gems/actionpack-4.0.4/lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
[bundle].../gems/actionpack-4.0.4/lib/action_dispatch/routing/route_set.rb:48:in `call'
[bundle].../gems/actionpack-4.0.4/lib/action_dispatch/journey/router.rb:71:in `block in call'
[bundle].../gems/actionpack-4.0.4/lib/action_dispatch/journey/router.rb:59:in `each'
[bundle].../gems/actionpack-4.0.4/lib/action_dispatch/journey/router.rb:59:in `call'
[bundle].../gems/actionpack-4.0.4/lib/action_dispatch/routing/route_set.rb:674:in `call'
[bundle].../gems/party_foul-1.5.3/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
[bundle].../gems/actionpack-4.0.4/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.0.4/lib/action_dispatch/middleware/flash.rb:241:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.0.4/lib/action_dispatch/middleware/cookies.rb:486:in `call'
[bundle].../gems/activerecord-4.0.4/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.0.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
[bundle].../gems/actionpack-4.0.4/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.0.4/lib/active_support/callbacks.rb:373:in `_run__1261865288663115632__call__callbacks'
[bundle].../gems/activesupport-4.0.4/lib/active_support/callbacks.rb:80:in `run_callbacks'
[bundle].../gems/actionpack-4.0.4/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.0.4/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
[bundle].../gems/actionpack-4.0.4/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/actionpack-4.0.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.0.4/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.0.4/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.0.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.0.4/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.0.4/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.0.4/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/actionpack-4.0.4/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/activesupport-4.0.4/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
[bundle].../gems/railties-4.0.4/lib/rails/engine.rb:511:in `call'
[bundle].../gems/railties-4.0.4/lib/rails/application.rb:97:in `call'
[bundle].../gems/railties-4.0.4/lib/rails/railtie/configurable.rb:30:in `method_missing'
/usr/local/Cellar/passenger/4.0.56/libexec/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
/usr/local/Cellar/passenger/4.0.56/libexec/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
/usr/local/Cellar/passenger/4.0.56/libexec/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
/usr/local/Cellar/passenger/4.0.56/libexec/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'</pre>
Fingerprint: `f0176d1d8c8f5128ab0c36f410619a6a04e868bf`

**Comment by stgm** [comment]
<table><tr><th>Occurred At</th><td>June 25, 2015 01:29:25 +0000</td></tr><tr><th>URL</th><td>[GET] /</td></tr><tr><th>Params</th><td><table><tr><th>controller</th><td>page</td></tr><tr><th>action</th><td>homepage</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>62.75.216.19</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td></td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0</td></tr><tr><th>Accept Encoding</th><td></td></tr><tr><th>Accept</th><td>*/*</td></tr></table></td></tr></table>
